config/routes.rb
Rails.application.routes.draw do
  root "boards#index"

  resources :boards do
    resources :lists do
      resources :tasks
    end
  end

  # post "/boards/2/lists/id/tasks/new", to: "tasks#update"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/board.rb
class Board < ApplicationRecord
  has_many :lists, dependent: :destroy
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :board
  has_many :tasks
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  before_action :set_board, except: [:index, :new, :create]
  def index
    # organize by descending order
    @boards = Board.except('order').order("id DESC")
  end

  def show
  end

  def new
    @board = Board.new
  end

  def edit
  end

  def create
    @board = Board.new(board_params)
    if @board.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def update
    if @board.update(board_params)
      redirect_to boards_path
    else
      render :edit
    end
  end

  def destroy
    @board.destroy
    redirect_to boards_path
  end

  private
    def set_board
      @board = Board.find(params[:id])
    end
    def board_params
      params.require(:board).permit(:name)
    end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, except: [:index, :new, :create]
  before_action :set_board
  def index
    # organize by descending order
    @lists = @board.lists.except('order').order("id DESC")
  end

  def show
  end

  def new
    @list = @board.lists.new
  end

  def edit
  end

  def create
    @list = @board.lists.new(list_params)
    if @list.save
      redirect_to boards_path
    else
      render :new
    end
  end

  def update
    if @list.update(list_params)
      redirect_to board_lists_path
    else
      render :edit
    end
  end

  def destroy
    @list.destroy
    redirect_to board_list_path
  end

  private
    def set_board
      @board = Board.find(params[:board_id])
    end
    def set_list
      @list = List.find(params[:id])
    end
    def list_params
      params.require(:list).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, except: [:index, :new, :create]
  before_action :set_list

  def index
    # organize by descending order
    @tasks = @list.tasks.except('order').order("id DESC")
  end

  def show
  end

  def new
    @task = @list.tasks.new
  end

  def edit
  end

  def create
    @task = @list.tasks.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to task_path
  end

  private
    def set_list
      @list = List.find(params[:list_id])
    end
    def set_task
      @task = Task.find(params[:id])
    end
    def task_params
      params.require(:task).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_form.html.erb
<%= form_with(model: board, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Board Name" %>
  </div>
  <br />
  <%= f.submit nil, class: "ui button primary"%>
<% end %>

app/views/boards/edit.html.erb
<h1>Boards#edit</h1>
<p>Find me in app/views/boards/edit.html.erb</p>

app/views/boards/index.html.erb
<div class = heading >
  <h2>Trello</h2>
  <div class="ui three item menu">
    <a class="item"><%= link_to nil, new_board_path%>New Board</a>
    <a class="item">button</a>
    <a class="item">button</a>
  </div>
  <hr/>
</div>

<% @boards.each do |board| %>
    <div class="ui card">
      <div class = "content">
        <div class="header">
          <%= board.name %>
        </div>
        <hr/>
        <% board.lists.each do |list| %>
          <%= link_to list.name, board_list_path(board.id, list.id), class: "ui button" %>
          <br/>
          <br/>
        <% end %>
        <%= link_to "Add a list...", new_board_list_path(board) %>
        <%= link_to "Delete", board, method: :delete, class: "ui basic orange card button"%>
      </div>
    </div>
<% end %> 

app/views/boards/new.html.erb
<div class = "heading">
  <h1>New Board</h1>
  <hr/>
</div>
<%= render "form", board: @board %>

app/views/boards/show.html.erb
<h1>Boards#show</h1>
<p>Find me in app/views/boards/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Trello</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= form_with(model: [@board, @list], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "List Name" %>
  </div>
  <br />
  <%= f.submit nil, class: "ui button primary"%>
<% end %>

app/views/lists/index.html.erb
<h1>Lists#index</h1>
<p>Find me in app/views/lists/index.html.erb</p>

app/views/lists/new.html.erb
<div class = "heading">
  <h2>New List</h2>
  <hr/>
</div>
<%= render "form", list: @list %>

app/views/lists/show.html.erb
<div class = "heading">
  <h2><%= @list.name %></h2>
  <%= link_to "Add Task...", new_board_list_task_path(@list, :id), class: "ui button" %>
  <%= link_to "Delete List", board_list_path(@board, @list), method: :delete, class: "ui button" %>
  <hr/>
</div>

app/views/tasks/_form.html.erb
<%= form_with(model: [@task, @list], local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Task Name" %>
  </div>
  <br />
  <%= f.submit nil, class: "ui button primary"%>
<% end %>

app/views/tasks/index.html.erb
<h1>Tasks#index</h1>
<p>Find me in app/views/tasks/index.html.erb</p>

app/views/tasks/new.html.erb
<div class = "heading">
  <h2>New Task</h2>
  <hr/>
</div>
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h1>Tasks#show</h1>
<p>Find me in app/views/tasks/show.html.erb</p>